/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-12-30 00:25:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fadmin._005fcs._005fnotice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1672359146940L));
    _jspx_dependants.put("jar:file:/C:/Users/java1/Desktop/Kmarket/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Kmarket/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/_admin/_header.jsp", out, false);
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	$(function() {\r\n");
      out.write("		\r\n");
      out.write("		if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.resultCode eq 101}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("			alert('게시물이 삭제되었습니다.');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//카테고리 선택\r\n");
      out.write("		$('select[name=cate]').change(function(){\r\n");
      out.write("			list($(this).val(), 1);\r\n");
      out.write("			paging($(this).val(), 1, 1);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		//게시물 삭제\r\n");
      out.write("		$(document).on('click','#delete',function(e){\r\n");
      out.write("			e.stopImmediatePropagation();\r\n");
      out.write("			let no = $(this).data(\"no\");\r\n");
      out.write("			//console.log(no);\r\n");
      out.write("			let del = confirm('게시물을 삭제하시겠습니까?');\r\n");
      out.write("			\r\n");
      out.write("			if(del){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : '/Kmarket/admin/cs/notice/delete.do',\r\n");
      out.write("					method : 'get',\r\n");
      out.write("					data : {'no' : no},\r\n");
      out.write("					dataType : 'json',\r\n");
      out.write("					success : function(data){\r\n");
      out.write("						if(data.result > 0){\r\n");
      out.write("							alert('게시물이 삭제되었습니다.');\r\n");
      out.write("							$('.all').prop(\"checked\",false);\r\n");
      out.write("							let cate = $('select[name=cate]').val();\r\n");
      out.write("							let pg = $('.current').data('pg');\r\n");
      out.write("							list(cate, pg);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		//전체선택\r\n");
      out.write("		$('.all').click(function(){\r\n");
      out.write("			if($(this).is(\":checked\")){\r\n");
      out.write("				$('.chk').prop(\"checked\",true);\r\n");
      out.write("			}else{\r\n");
      out.write("				$('.chk').prop(\"checked\",false);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		$(document).on('click','#chk',function(e){\r\n");
      out.write("			e.stopImmediatePropagation();\r\n");
      out.write("			$('.all').prop(\"checked\",false);\r\n");
      out.write("			if($('input[name=chk]:checked').length == $('.chk').length){\r\n");
      out.write("				$('.all').prop(\"checked\",true);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		//선택삭제\r\n");
      out.write("		$('.selectDelete').click(function(){\r\n");
      out.write("			if($('input[name=chk]:checked').length == 0){\r\n");
      out.write("				alert('선택된 게시물이 없습니다.');\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			let answer = confirm('게시물을 삭제하시겠습니까?');\r\n");
      out.write("			if(answer){\r\n");
      out.write("				let chkArr = new Array();\r\n");
      out.write("				$('input[name=chk]:checked').each(function(){\r\n");
      out.write("					chkArr.push($(this).data(\"no\"));\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : '/Kmarket/admin/cs/notice/delete.do',\r\n");
      out.write("					method : 'post',\r\n");
      out.write("					data : {'chkArr' : chkArr},\r\n");
      out.write("					traditional: true,\r\n");
      out.write("					dataType : 'json',\r\n");
      out.write("					success : function(data){\r\n");
      out.write("						if(data.result > 0){\r\n");
      out.write("							alert('게시물이 삭제되었습니다.');\r\n");
      out.write("							$('.all').prop(\"checked\",false);\r\n");
      out.write("							let cate = $('select[name=cate]').val();\r\n");
      out.write("							let pg = $('.current').data('pg');\r\n");
      out.write("							list(cate, pg);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		//console.log('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' + '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("		list('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("		paging('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', Math.ceil('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(Math.ceil(param.pg/10)-1) * 10 + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'), '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		//리스트출력\r\n");
      out.write("		function list(cate, pg){\r\n");
      out.write("			let intPg = parseInt(pg);\r\n");
      out.write("			//console.log(intPg);\r\n");
      out.write("			let jsonData = {\r\n");
      out.write("				'cate' : cate,\r\n");
      out.write("				'pg' : pg\r\n");
      out.write("			};\r\n");
      out.write("			\r\n");
      out.write("			//console.log(jsonData);\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : '/Kmarket/admin/cs/notice/list.do',\r\n");
      out.write("				method : 'post',\r\n");
      out.write("				data : jsonData,\r\n");
      out.write("				dataType : 'json',\r\n");
      out.write("				async: false,\r\n");
      out.write("				success : function(data){\r\n");
      out.write("					$('.notice_list').remove();\r\n");
      out.write("					if(data.length > 0){\r\n");
      out.write("						let i = (intPg-1) * 10 + 1;\r\n");
      out.write("						for(let article of data){\r\n");
      out.write("							let tag = \"<tr class='notice_list'>\";\r\n");
      out.write("								tag +=\"<td><input type='checkbox' name='chk' class='chk' id='chk' data-no='\"+article.no+\"'></td>\";\r\n");
      out.write("								tag += \"<td>\"+i+\"</td>\";\r\n");
      out.write("								tag += \"<td>\"+article.cate+\"</td>\";\r\n");
      out.write("								tag += \"<td><a href='/Kmarket/admin/cs/notice/view.do?no=\"+article.no+\"&cate=\"+cate+\"&pg=\"+pg+\"'>\"+article.title+\"</a></td>\";\r\n");
      out.write("								tag += \"<td>\"+article.hit+\"</td>\";\r\n");
      out.write("								tag += \"<td>\"+article.rdate+\"</td>\";\r\n");
      out.write("								tag += \"<td><a href='#' id='delete' data-no='\"+article.no+\"'>[삭제]</a><a href='/Kmarket/admin/cs/notice/modify.do?no=\"+article.no+\"&cate=\"+cate+\"&pg=\"+pg+\"'>[수정]</a></td>\";\r\n");
      out.write("								tag += \"</tr>\";\r\n");
      out.write("							i += 1;\r\n");
      out.write("							$('.admin_cs_list_div').children('table').append(tag);\r\n");
      out.write("						}\r\n");
      out.write("						return;\r\n");
      out.write("					}else{\r\n");
      out.write("						let tag = \"<tr class='notice_list'>\";\r\n");
      out.write("							tag += \"<td colspan='8' align='center'>등록된 공지사항이 없습니다.</td> \"\r\n");
      out.write("							tag += \"</tr>\";\r\n");
      out.write("							$('.admin_cs_list_div').children('table').append(tag);\r\n");
      out.write("						return;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//페이징\r\n");
      out.write("		function paging(cate, pg, current){\r\n");
      out.write("			let jsonData = {\r\n");
      out.write("				'cate' : cate,\r\n");
      out.write("				'pg' : pg\r\n");
      out.write("			};\r\n");
      out.write("		\r\n");
      out.write("			//console.log(jsonData + current);\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : '/Kmarket/admin/cs/notice/page.do',\r\n");
      out.write("				method : 'get',\r\n");
      out.write("				data : jsonData,\r\n");
      out.write("				dataType : 'json',\r\n");
      out.write("				async: false,\r\n");
      out.write("				success : function(data){\r\n");
      out.write("					$('.page').empty();\r\n");
      out.write("					if(data.pageGroupEnd > data.lastPageNum){\r\n");
      out.write("						data.pageGroupEnd = data.lastPageNum;\r\n");
      out.write("					}\r\n");
      out.write("						let tag = \"\";\r\n");
      out.write("						if(data.pageGroupStart > 1){\r\n");
      out.write("							tag += \"<a href='#page' id='prev' class='prev' data-last='\"+ data.pageGroupStart +\"'><&nbsp;이전</a>\";\r\n");
      out.write("						}\r\n");
      out.write("						for(let i=data.pageGroupStart; i<=data.pageGroupEnd; i++){\r\n");
      out.write("							tag += \"<a href='#page' id='num' data-pg='\"+i+\"' class=\" + (i==current ? 'current':'off') + \">\"+i+\"</a>\";\r\n");
      out.write("						}\r\n");
      out.write("						if(data.lastPageNum > data.pageGroupEnd){\r\n");
      out.write("							tag += \"<a href='#page' id='next' class='next' data-last='\"+ data.pageGroupEnd +\"'>다음&nbsp;></a>\";\r\n");
      out.write("						}\r\n");
      out.write("					$('.page').append(tag);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//페이지 클릭\r\n");
      out.write("		$(document).on('click','#num',function(e){\r\n");
      out.write("			e.stopImmediatePropagation();\r\n");
      out.write("			let cate = $('select[name=cate]').val();\r\n");
      out.write("			let pg = $(this).data('pg');\r\n");
      out.write("			\r\n");
      out.write("			$('a#num').addClass(\"off\").removeClass(\"current\");\r\n");
      out.write("		    $(this).addClass(\"current\").removeClass(\"off\");\r\n");
      out.write("		    \r\n");
      out.write("			list(cate, pg);\r\n");
      out.write("		});\r\n");
      out.write("		$(document).on('click', '#prev',function(e) {\r\n");
      out.write("	    	e.stopImmediatePropagation();\r\n");
      out.write("	    	let cate = $('select[name=cate]').val();\r\n");
      out.write("	    	let pg = $(this).data('last');\r\n");
      out.write("	    	list(cate, pg-1);\r\n");
      out.write("	    	paging(cate, pg-10, pg-1);\r\n");
      out.write("	    }); \r\n");
      out.write("		$(document).on('click', '#next',function(e) {\r\n");
      out.write("	    	e.stopImmediatePropagation();\r\n");
      out.write("	    	let cate = $('select[name=cate]').val();\r\n");
      out.write("			let pg = $(this).data('last');\r\n");
      out.write("			list(cate, pg+1);\r\n");
      out.write("			paging(cate, pg+1, pg+1);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$('.register').click(function(){\r\n");
      out.write("			location.href =\"/Kmarket/admin/cs/notice/write.do\";\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	 });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("            <section id=\"admin-index\">\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <h3>공지사항 목록</h3>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        HOME > 고객센터 > <strong>공지사항</strong>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <div id=\"admin_cs_list\">\r\n");
      out.write("                <div class=\"group\">\r\n");
      out.write("                    <select name=\"cate\" id=\"cate\">\r\n");
      out.write("                    	<option value=\"전체보기\"  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" >전체보기</option>\r\n");
      out.write("	                    <option value=\"고객 서비스\" ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" >고객 서비스</option>\r\n");
      out.write("	                    <option value=\"안전거래\" ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write(" >안전거래</option>\r\n");
      out.write("	                    <option value=\"위해상품\" ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(" >위해상품</option>\r\n");
      out.write("	                    <option value=\"이벤트 당첨\" ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write(" >이벤트 당첨</option>\r\n");
      out.write("                	</select>\r\n");
      out.write("                	</div>\r\n");
      out.write("                    <div class=\"admin_cs_list_div\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                           <tr>\r\n");
      out.write("                               <th><input type=\"checkbox\" class=\"all\"/></th>\r\n");
      out.write("                               <th>번호</th>\r\n");
      out.write("                               <th>유형</th>\r\n");
      out.write("                               <th>제목</th>\r\n");
      out.write("                               <th>조회</th>\r\n");
      out.write("                               <th>날짜</th>\r\n");
      out.write("                               <th>관리</th>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                          <tr class=\"notice_list\"></tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <div class=\"btn\">\r\n");
      out.write("                            <button class=\"btn_gray selectDelete\">선택삭제</button>\r\n");
      out.write("                            <button class=\"btn_blue register\">작성하기</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"page\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </main>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/_admin/_footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /_admin/_cs/_notice/list.jsp(221,43) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cate == '전체보기'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected=\"selected\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /_admin/_cs/_notice/list.jsp(222,44) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cate == '고객 서비스'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected=\"selected\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /_admin/_cs/_notice/list.jsp(223,42) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cate == '안전거래'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected=\"selected\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /_admin/_cs/_notice/list.jsp(224,42) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cate == '위해상품'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected=\"selected\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /_admin/_cs/_notice/list.jsp(225,44) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cate == '이벤트'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected=\"selected\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
