/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-12-30 00:25:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fadmin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _005fheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1672359146940L));
    _jspx_dependants.put("jar:file:/C:/Users/java1/Desktop/Kmarket/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Kmarket/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Kmarket</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/Kmarket/css/css_admin.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/20962f3e4b.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Kmarket/smarteditor/js/HuskyEZCreator.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"/Kmarket/_admin/admin_js/validation.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $('#gnb > li > a').click(function(){\r\n");
      out.write("            $(this).siblings().slideToggle(300);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"admin-wrapper\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div>\r\n");
      out.write("                <a href=\"/Kmarket/index.do\" class=\"indexlogo\">\r\n");
      out.write("                    <img src=\"/Kmarket/img/img_cs/logo.png\" alt=\"k마켓로고\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"/Kmarket/admin/index.do\" class=\"logo\">\r\n");
      out.write("                    <img src=\"/Kmarket/img/img_admin/admin_logo.png\" alt=\"로고\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <p>\r\n");
      out.write("                    <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessUser.company}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 반갑습니다. &nbsp;&nbsp; </span>\r\n");
      out.write("                    <a href=\"/Kmarket/admin/index.do\">HOME |</a>\r\n");
      out.write("                    <a href=\"/Kmarket/logout.do\">로그아웃 |</a>\r\n");
      out.write("                    <a href=\"/Kmarket/cs/index.do\">고객센터</a>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <main>\r\n");
      out.write("            <aside>\r\n");
      out.write("                <ul id=\"gnb\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fa fa-cogs\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            환경설정\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li><a href=\"#\">기본환경설정</a></li>\r\n");
      out.write("                            <li><a href=\"#\">배너관리</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-store\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            상점관리\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li><a href=\"#\">판매자현황</a></li>\r\n");
      out.write("                            <li><a href=\"/Kmarket/admin/product/list.do\">재고관리</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fa fa-users\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            회원관리\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li><a href=\"#\">회원현황</a></li>\r\n");
      out.write("                            <li><a href=\"#\">포인트관리</a></li>\r\n");
      out.write("                            <li><a href=\"#\">비회원관리</a></li>\r\n");
      out.write("                            <li><a href=\"#\">접속자집계</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fas fa-box-open\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            상품관리\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li><a href=\"/Kmarket/admin/product/list.do?company=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessUser.company}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&level=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessUser.level}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">상품현황</a></li>\r\n");
      out.write("                            <li><a href=\"/Kmarket/admin/product/register.do\">상품등록</a></li>\r\n");
      out.write("                            <li><a href=\"/Kmarket/admin/product/list.do\">재고관리</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fa fa-credit-card\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            주문관리\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ol>\r\n");
      out.write("                            <li><a href=\"#\">주문현황</a></li>\r\n");
      out.write("                            <li><a href=\"#\">매출현황</a></li>\r\n");
      out.write("                            <li><a href=\"#\">결제관리</a></li>\r\n");
      out.write("                            <li><a href=\"#\">배송관리</a></li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </aside>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /_admin/_header.jsp(100,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessUser.level eq 7}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li>\r\n");
          out.write("	                        <a href=\"#\">\r\n");
          out.write("	                            <i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i>\r\n");
          out.write("	                            게시판관리\r\n");
          out.write("	                        </a>\r\n");
          out.write("	                        <ol>\r\n");
          out.write("	                            <li><a href=\"/Kmarket/admin/cs/notice/list.do?cate=전체보기&pg=1\">공지사항</a></li>\r\n");
          out.write("	                            <li><a href=\"/Kmarket/admin/cs/faq/list.do\">자주묻는 질문</a></li>\r\n");
          out.write("	                            <li><a href=\"/Kmarket/admin/cs/qna/list.do\">문의하기</a></li>\r\n");
          out.write("	                        </ol>\r\n");
          out.write("	                    </li>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
