/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-12-23 04:41:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._005fadmin._005fproduct;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/_admin/_header.jsp", out, false);
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("	$('#cate1').change(function(){\r\n");
      out.write("		let cate1 = $(this).val();\r\n");
      out.write("		$('#cate2').empty();\r\n");
      out.write("		let jsonData = {\r\n");
      out.write("				'cate1' : cate1\r\n");
      out.write("		}\r\n");
      out.write("		console.log(jsonData);\r\n");
      out.write("		\r\n");
      out.write("	 	$.ajax({\r\n");
      out.write("		    url : '/Kmarket/admin/product/findCate2.do',\r\n");
      out.write("		    method : 'get',\r\n");
      out.write("		    data: jsonData,\r\n");
      out.write("		    dataType: 'json',\r\n");
      out.write("		    success: function (data) {\r\n");
      out.write("		    	for(let cate2 of data){\r\n");
      out.write("		    		let tag = \"<option value= \"+cate2.cate2+\">\"+cate2.c2Name+\"</option>\";\r\n");
      out.write("		    		$('#cate2').append(tag);\r\n");
      out.write("		    	}\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <section id=\"admin-product-register\">\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <h3>상품등록</h3>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        HOME > 상품관리 > <strong>상품등록</strong>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <article>\r\n");
      out.write("                    <form action=\"/Kmarket/admin/product/register.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                        <!-- 상품분류 -->\r\n");
      out.write("                        <section>\r\n");
      out.write("                            <h4>상품분류</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                기본분류는 반드시 선택하셔야 합니다. 하나의 상품에 1개의 분류를 지정 합니다.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <table>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>1차 분류</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"cate1\" id = \"cate1\">\r\n");
      out.write("                                            <option value= \"10\">브랜드패션</option>\r\n");
      out.write("                                            <option value= \"11\">패션·의류·뷰티</option>\r\n");
      out.write("                                            <option value= \"12\">유아동</option>\r\n");
      out.write("                                            <option value= \"13\">식품·생필품</option>\r\n");
      out.write("                                            <option value= \"14\">홈데코·문구·취미·반려</option>  \r\n");
      out.write("                                            <option value= \"15\">컴퓨터·디지털·가전</option>                                              \r\n");
      out.write("                                            <option value= \"16\">스포츠·건강·렌탈</option>                                              \r\n");
      out.write("                                            <option value= \"17\">자동차·공구</option>                                              \r\n");
      out.write("                                            <option value= \"18\">여행·도서·티켓·e쿠폰</option>                                              \r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                      <td>2차 분류</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"cate2\" id=\"cate2\">\r\n");
      out.write("                                            <option value=\"10\">브랜드 여성의류</option>\r\n");
      out.write("                                            <option value=\"11\">브랜드 남성의류</option>\r\n");
      out.write("                                            <option value=\"12\">브랜드 진/캐쥬얼</option>\r\n");
      out.write("                                            <option value=\"13\">브랜드 신발/가방</option>\r\n");
      out.write("                                            <option value=\"14\">브랜드 쥬얼리/시계</option>\r\n");
      out.write("                                            <option value=\"15\">브랜드 아웃도어</option>             \r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>    \r\n");
      out.write("                            </table>\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <!-- 기본정보 -->\r\n");
      out.write("                        <section>\r\n");
      out.write("                            <h4>기본정보</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                기본정보는 반드시 입력해야 합니다.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <table>\r\n");
      out.write("                                <tbody><tr>\r\n");
      out.write("                                    <td>상품명</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"prodName\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>기본설명</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span>상품명 하단에 상품에 대한 추가적인 설명이 필요한 경우에 입력</span>\r\n");
      out.write("                                        <input type=\"text\" name=\"descript\">\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>제조사</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"company\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                 <tr>\r\n");
      out.write("                                    <td>판매자</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"seller\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>판매가격</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"price\">원</td>\r\n");
      out.write("                                </tr>                                    \r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>할인율</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span>0을 입력하면 할인율 없음</span>\r\n");
      out.write("                                        <input type=\"text\" name=\"discount\">율\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>포인트</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span>0을 입력하면 포인트 없음</span>\r\n");
      out.write("                                        <input type=\"text\" name=\"point\">점\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>재고수량</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"stock\">개</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>배송비</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span>0을 입력하면 배송비 무료</span>\r\n");
      out.write("                                        <input type=\"text\" name=\"delivery\">원\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>상품 썸네일</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span>크기 120 x 120, 상품 목록에 출력될 이미지 입니다. </span>\r\n");
      out.write("                                        <input type=\"file\" name=\"thumb1\">\r\n");
      out.write("\r\n");
      out.write("                                        <span>크기 240 x 240, 상품 메인에 출력될 이미지 입니다. </span>\r\n");
      out.write("                                        <input type=\"file\" name=\"thumb2\">\r\n");
      out.write("\r\n");
      out.write("                                        <span>크기 480 x 480, 상품 상세에 출력될 이미지 입니다. </span>\r\n");
      out.write("                                        <input type=\"file\" name=\"thumb3\">\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>상세 상품정보</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span>크기 가로 940px 높이 제약없음, 크기 최대 1MB, 상세페이지 상품정보에 출력될 이미지 입니다.</span>\r\n");
      out.write("                                        <input type=\"file\" name=\"detail\">\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody></table>                                \r\n");
      out.write("                        </section>\r\n");
      out.write("                        <!-- 상품정보 제공 고시 -->\r\n");
      out.write("                        <section>\r\n");
      out.write("                            <h4>상품정보 제공고시</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                [전자상거래에 관한 상품정보 제공에 관한 고시] 항목에 의거 등록해야 되는 정보입니다.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <table>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("<!--                                 <tr> -->\r\n");
      out.write("<!--                                     <td>상품번호</td> -->\r\n");
      out.write("<!--                                     <td><input type=\"text\" name=\"\"></td> -->\r\n");
      out.write("<!--                                 </tr> -->\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>상품상태</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"status\" value=\"새상품\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>부가세 면세여부</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"duty\" value=\"과세상품\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>영수증발행</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"receipt\" value=\"발행가능-신용카드 전표, 온라인 현금영수증\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>사업자구분</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"bizType\" value=\"사업자 판매자\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>브랜드</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"brand\" value=\"국내산\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>원산지</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"origin\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>제품소재</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"material\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>색상</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"color\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>치수</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"size\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>제조자/수입국</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"manufacturer\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>제조국</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"country\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>취급시 주의사항</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"precautions\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>제조연월</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"date\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>품질보증기준</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"standard\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>A/S 책임자와 전화번호</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"as\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>주문후 예상 배송기간</td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"delivery_date\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody></table>  \r\n");
      out.write("                                   <input type=\"submit\" name=\"submit_product\"  class = \"register_btn\" value=\"등록하기\">                       \r\n");
      out.write("                        </section>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </article>\r\n");
      out.write("                <p class=\"ico alert\">\r\n");
      out.write("                    <strong>Warning!</strong>\r\n");
      out.write("                    전자상거래 등에서의 상품 등의 정보제공에 관한 고시에 따라 총 35개 상품군에 대해 상품 특성 등을 양식에 따라 입력할 수 있습니다.\r\n");
      out.write("                </p>\r\n");
      out.write("            </section>\r\n");
      out.write("        </main>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/_admin/_footer.jsp", out, false);
      out.write("\r\n");
      out.write("        ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
